### ISSUE TITLE
[Deliverable 1]

### ISSUE THREAD

**Issue by clarkh97** [Berea-CS-Courses/capstone-project-clarkh97#3]
This document is my project specification. It goes into a bit more detail on the purpose of my project.

**Comment by belainehi** [comment]
Thanks for creating an issue. Make sure that you do them for all Deliverables requiring issues. 
Feedback: It is great how you set the scope of what is achievable during the semester and your overview looks good too. You can clarify some of the functional requirements such as "software must calculate emissions based on vehicle and driving info." Will the software require any more information besides the car model, emission information and if the car is in drive or park mode? Does driving info mean driving speed? If so wouldn't that be part of the calculation the software does based on the user's location change? Do you think you'll have enough time to build an android and an iOS app? These questions are just clarifying questions, your D1 looks good overall.

**Comment by belainehi** [comment]
@clarkh97 Please close this issue and create a separate issue for Deliverable 2.
